### ISSUE TITLE
doesn't build on windows

### ISSUE THREAD

**Issue by askmike** [soyuka/relieve#2]
See [this issue](https://github.com/askmike/gekko/issues/456).

Just a FYI!

**Comment by soyuka** [comment]
Oh, sad you removed the dependency for that :cat: 

Ofc, windows has no `bash` function, still it should not be blocking. I'll fix this asap thanks!

**Comment by askmike** [comment]
I will add it back as soon as it works :)

That project wasn't actually using relieve just yet (the whole flow is a single node process), but will in the future (if it works on windows)!

**Comment by soyuka** [comment]
Great, wonder if it works on windows actually! (it should)

Note, I have a work in progress on the library allowing the master to be killed by leaving child up and then re-attaching to them. Also the concept of task Interfaces is not documented yet (for example I added a [Logger](https://github.com/soyuka/relieve-logger) that integrates seamlessly to the library).

Nice work about gekko btw.

**Comment by soyuka** [comment]
Added appveyor, should be just fine on windows! https://ci.appveyor.com/project/soyuka/relieve

**Comment by askmike** [comment]
Awesome! Will check it out asap. Thanks for the quick fix.
